### ISSUE TITLE
Warnings on Tokay2 about Missing Links in the Documentation

### ISSUE THREAD

**Issue by const-ae** [Bioconductor/MatrixGenerics#11]
Hey Pete, 

I just noticed that CHECK for `sparseMatrixStats` has many warnings which derive from `MatrixGenerics` http://bioconductor.org/checkResults/devel/bioc-LATEST/MatrixGenerics/tokay2-checksrc.html

There was recently some discussion on the Bioc-devel mailing list on a similar issue https://stat.ethz.ch/pipermail/bioc-devel/2020-April/016552.html

I just wanted to check if you are already looking into this? Otherwise I could try to draft a fix, but I cannot promising anything, because I have two deadlines until the end of the week 😅

**Comment by PeteHaitch** [comment]
Thanks for the report, I'll fix this week

**Comment by const-ae** [comment]
Great :)

**Comment by PeteHaitch** [comment]
Should be fixed by 87967842f1be01fd1b2a8ba06b1d961104a65395.
It gets a clean check on my Windows VM, at least.

**Comment by const-ae** [comment]
Nice, thank you for taking care :)

**Comment by const-ae** [comment]
Hi Pete, 

there are still problems with the missing links for functions that are documented in a different Rd file in `matrixStats`: http://bioconductor.org/checkResults/devel/bioc-LATEST/MatrixGenerics/tokay2-checksrc.html

I created a pull request #12 that hopefully fixes the problem. However, I don't have a windows machine, so it would be great if you could test the fix.

Best, Constantin

**Comment by PeteHaitch** [comment]
Yeah I saw those warnings. I'll deal with them after the release
