### ISSUE TITLE
test-api_compatibility.R needs an update to accommodate an upcoming change in matrixStats

### ISSUE THREAD

**Issue by hpages** [Bioconductor/MatrixGenerics#17]
@const-ae Hi Constantin,

Do you think you can take care of [this](https://github.com/HenrikBengtsson/matrixStats/issues/183#issuecomment-705901526)?

Thanks,
H.

**Comment by const-ae** [comment]
Sure, I'll take a look

**Comment by PeteHaitch** [comment]
Closed by #18
