### ISSUE TITLE
Build Report Warning: File link 'rowRanges' in package 'SummarizedExperiment' does not exist

### ISSUE THREAD

**Issue by const-ae** [Bioconductor/MatrixGenerics#19]
I just checked the build report and noticed that there is a [WARNING](https://bioconductor.org/checkResults/3.12/bioc-LATEST/MatrixGenerics/tokay1-checksrc.html) on windows concerning the documentation of rowRanges

```
Found the following significant warnings:
  Rd warning: C:/Users/biocbuild/bbs-3.12-bioc/tmpdir/RtmpolctSY/R.INSTALLea848f42b6d/MatrixGenerics/man/rowRanges.Rd:62: file link 'RangedSummarizedExperiment' in package 'SummarizedExperiment' does not exist and so has been treated as a topic
  Rd warning: C:/Users/biocbuild/bbs-3.12-bioc/tmpdir/RtmpolctSY/R.INSTALLea848f42b6d/MatrixGenerics/man/rowRanges.Rd:63: file link 'rowRanges' in package 'SummarizedExperiment' does not exist and so has been treated as a topic
```

As the deadline is tomorrow, does anyone have capacity to fix the issue today? I assume the problem was introduced here by @hpages's commit to make `rowRanges` compatible with `SummarizedExperiment` (https://github.com/Bioconductor/MatrixGenerics/commit/8b10d19bdf33c572d99767eae90fa500f1b40ae4#diff-d387fdcf206554302df9d454f50dd59442df365e2899b5afb221307fb21a6e10R25).

**Comment by hpages** [comment]
I tend to ignore these "treated as a topic" warnings on Windows as the whole thing makes little sense. Anyways I agree that the warnings don't make MatrixGenerics look good so I'll look into it. Don't worry too much about tomorrow's deadline.

**Comment by mtmorgan** [comment]
I *think* that R-devel (to be used in the Bioconductor 3.13 builds) addresses this so that it is not a NOTE... From the NEWS.Rd:
```
     \item For HTML help (both dynamic and static), Rd file links to
      help pages in external packages are now treated as references to
      topics rather than file names, and falls back to a file link only
      if the topic is not found in the target package. The earlier rule
      which prioritized file names over topics can be restored by
      setting the environment variable \env{_R_HELP_LINKS_TO_TOPICS_} to
      a false value.
```

**Comment by hpages** [comment]
Finally! Great news

**Comment by hpages** [comment]
I don't understand why that would even be a NOTE but it's a day to celebrate not to complain ;-)

**Comment by LiNk-NY** [comment]
This looks to have been resolved...
