### ISSUE TITLE
Issue with  matrixStats (>= 0.60.1)

### ISSUE THREAD

**Issue by evanbiederstedt** [Bioconductor/MatrixGenerics#27]
Hi there

I have some errors in my CI/CD pipeline related to MatrixGenerics. 

From what I see here, the package depends on `matrixStats (>= 0.60.1)`: https://github.com/Bioconductor/MatrixGenerics/blob/master/DESCRIPTION#L24

http://bioconductor.org/packages/release/bioc/html/MatrixGenerics.html

This results in an error, as the version on CRAN is only 0.60.0

Indeed, the version on GitHub also doesn't go up to 0.60.1:
https://github.com/HenrikBengtsson/matrixStats/blob/develop/DESCRIPTION

If I understand the situation correctly, could you possibly fix this?  I think `matrixStats (>= 0.60.0)` would solve this, no?
CC @HenrikBengtsson

Best, Evan

**Comment by HenrikBengtsson** [comment]
> ,,, as the version on CRAN is only 0.60.0

The version on CRAN is 0.61.0, cf. https://cran.r-project.org/package=matrixStats

**Comment by evanbiederstedt** [comment]
Uff, sorry; I misread.....sorry about that.

In that case, let me debug my CI pipeline :)

Sorry for the false alarm---apologies for wasting your time. I appreciate the quick response @HenrikBengtsson 

Issue closed.
