### ISSUE TITLE
Patch 1.12.1 not 100% backward compatible

### ISSUE THREAD

**Issue by const-ae** [Bioconductor/MatrixGenerics#34]
I just tried to make the released version of `sparseMatrixStats` compatible with the patched version of `MatrixGenerics` (v.1.12.1). I noticed that in some corner cases the behavior did change compared with the previous version 1.12.0

For example, `colMeans` with a `center` argument used to return a named output:
``` r
mat <- matrix(1:12, nrow = 4, ncol = 3)
colnames(mat) <- c("A", "B", "C")

center <- matrixStats::colMeans2(mat)
MatrixGenerics::colVars(mat, center = center, useNames = NA)
#>        A        B        C
#> 1.666667 1.666667 1.666667

packageVersion("MatrixGenerics")
#> [1] '1.12.0'
packageVersion("matrixStats")
#> [1] '0.62.0'
```

<sup>Created on 2023-06-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

But now it doesn't have names anymore:
``` r
mat <- matrix(1:12, nrow = 4, ncol = 3)
colnames(mat) <- c("A", "B", "C")

center <- matrixStats::colMeans2(mat)
MatrixGenerics::colVars(mat, center = center, useNames = NA)
#> [1] 1.666667 1.666667 1.666667

packageVersion("MatrixGenerics")
#> [1] '1.12.1'
packageVersion("matrixStats")
#> [1] '1.0.0'
```

<sup>Created on 2023-06-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

----------

The same problem occurs for `colWeightedMedians`

**Comment by hpages** [comment]
Thanks Constantin. Good catch! So it looks like with **matrixStats** < 1.0.0, whether a function propagates the names or not (when called with `useNames=NA`) is not a simple yes or no answer. It's more like a "it depends" kind of answer!

I'll make the correction today for `colVars`/`rowVars`, `colSds`/`rowSds`, and `colWeightedMedians`/`rowWeightedMedians`.

**Comment by hpages** [comment]
Done in **MatrixGenerics** 1.12.2 (see 29f77e7197a38df960fd39488327842ac7a65c06)
