### ISSUE TITLE
Missing `matrixStats`'s  `digits` arg in `rowQuantiles()`

### ISSUE THREAD

**Issue by bnprks** [Bioconductor/MatrixGenerics#39]
It looks like `matrixStats` updated the signature of `rowQuantiles()` and `colQuantiles()` to include a new `digits` argument last year ([commit 5e9be8](https://github.com/HenrikBengtsson/matrixStats/commit/5e9be8b280428a41fea14418d92119c29b9f7116)).

I'm trying to write a few functions consistent with the `matrixStats` interface, but also register the appropriate methods in `MatrixGenerics` if it is installed. The signature mismatch causes some minor issues (though we have workarounds). 

I know it's a minor thing, but I was wondering if you would consider adding `digits` to the `MatrixGenerics` signature so that it matches with `matrixStats`?

**Comment by LiNk-NY** [comment]
cc: @PeteHaitch @hpages

**Comment by PeteHaitch** [comment]
Thanks for the report, @bnprks, I hadn't seen that.

I won't have time to make this change before the [upcoming release](https://bioconductor.org/developers/release-schedule/) (and I'm also wary of introducing it so close to the release, even though it's probably a minor change).
Are your functions for a current Bioconductor package or a forthcoming one that could wait until after the release?

**Comment by hpages** [comment]
Hi Pete, I've started to look into this. I can make the change if you don't have time. Last time I checked, no package in Bioconductor was using these generics, except **DelayedMatrixStats**, so I don't expect the change to cause too much damage.

BTW I thought the unit tests in **MatrixGenerics** would be able to catch it when the argument lists of the generics in **MatrixGenerics** become out-of-sync with **matrixStats**, but apparently they don't. Maybe that's something we should try to address in the future.

**Comment by hpages** [comment]
Done.

Oh, and the reason the unit tests didn't catch this is because the `.check_formals()` function in `tests/testthat/generate_tests_helper_script.R` was explicitely dropping the `digits` argument from the **matrixStats** formals with:
```
if (fnc_name %in% c("rowQuantiles", "colQuantiles"))
    matrixStats_formals$digits <- NULL
```
before comparing them with the formals of the generics in **MatrixGenerics**. So it seems that the `digits` argument in **matrixStats** has been around for a while, but that, for some reason, it was purposedly ommitted in **MatrixGenerics**. No idea why `¯\_(ツ)_/¯`

**Comment by kuwisdelu** [comment]
> Last time I checked, no package in Bioconductor was using these generics, except **DelayedMatrixStats**, so I don't expect the change to cause too much damage.

I will likely use them at some point but haven’t had time yet. ;-)

**Comment by PeteHaitch** [comment]
Thanks, Hervé!

**Comment by bnprks** [comment]
Thanks for the very fast fix Hervé!

@PeteHaitch, the package I'm working on is BPCells -- currently [github only](https://github.com/bnprks/BPCells), but planning to submit to CRAN rather than BioConductor (in part to help with compatibility for Seurat users that depend on BPCells). It's focused on high-performance disk-backed scATAC and scRNA-seq analysis, implementing a narrow scope of matrix operations but trying to make them run quite quickly.

No worries if this misses the active release window. This discrepancy was found by @immanuelazn when the main symptom was our roxygen2 docs getting confused by the signature mismatch. I expect any user-facing incompatibilities would be rare, but it'll be nice to have matching function signatures in the long run.

We don't take a hard dependency on either matrixStats or MatrixGenerics, but if either is present at load time we will set up method dispatching as best we can. It's not perfect, but preserves compatibility in most cases. I think our setup works fine without MatrixGenerics needing any BPCells-specific code, so it's probably the simplest approach for now. (here's an example of how the dispatch works: [commit](https://github.com/bnprks/BPCells/commit/383690a26b35d92e174f9df71452b4a6eb9a98b6#diff-76cfc1e06c5fa0d2fd252296c9fc442c0c8d04cb82d0ebbd9d06347ebb01ec5d))
