### ISSUE TITLE
BioConductor Submission

### ISSUE THREAD

**Issue by const-ae** [Bioconductor/MatrixGenerics#7]
I believe the package is now almost ready for submission.

I ran checks with winbuilder and rhub, which were fine. 
However, `BiocCheck` complained about the following things:

1. `NOTE: Consider adding these automatically suggested biocViews: DataImport`
2. `NOTE: Consider adding a NEWS file, so your package news will be included in Bioconductor release announcements.`
3. `Consider shorter lines; 473 lines (7%) are > 80 characters long.`
4. `NOTE: Consider multiples of 4 spaces for line indents, 1066 lines(17%) are not.`
5. ` Cannot determine whether maintainer is subscribed to the bioc-devel mailing list`

I would tend to ignore NOTE 1, 3, 4, and 5. About 2, I am not quite sure what to put into a NEWS for a new submission.

Two additional things, that we should think about:

1. There is no vignette at the moment for this package. Does it makes sense for such a package to have one. And if yes, what would we put in there?
2. @PeteHaitch, you are at the moment listed as the `cre` role in the DESCRIPTION. This would mean, that you would have to take care of the submission process, I believe. I can also take care of the submission, but am not sure what the appropriate role would then be.

Best, Constantin

**Comment by PeteHaitch** [comment]
> I would tend to ignore NOTE 1, 3, 4, and 5. About 2, I am not quite sure what to put into a NEWS for a new submission.

My 2 cents: NOTE 1 seems a false-positive, 2 I think we should have (it might just be a skeleton for future releases), 3 is nice to have but not essential, 4 I also ignore because I use 2-space tabs, 5 is easily fixed (my email in the DESCRIPTION is subscribed to bioc-devel, perhaps yours isnt'?)

> 1. There is no vignette at the moment for this package. Does it makes sense for such a package to have one. And if yes, what would we put in there?

The vignette would be developer-focused I think. It could conceivably give some examples of writing some methods for a novel matrix-like class. I don't think this is essential for the first submission but others may disagree.

> 2. @PeteHaitch, you are at the moment listed as the cre role in the DESCRIPTION. This would mean, that you would have to take care of the submission process, I believe. I can also take care of the submission, but am not sure what the appropriate role would then be.

Okay, I will submit this by the end of this week.
I will tag you in the issue and add a brief note to the submission that you may also respond to reviewer's comments etc.
I will also work on a branch of **DelayedMatrixStats** that uses **MatrixGenerics**  so I can add it to devel as soon as **MatrixGenerics** is accepted.
Thank you for leading the charge on this, @const-ae!

**Comment by const-ae** [comment]
> Okay, I will submit this by the end of this week.

Great! Thank you for your support. 

I will then shift my focus and will try to get `sparseMatrixStats` ready as well :)

**Comment by LTLA** [comment]
I, too, am looking forward to this.

Note that **DelayedMatrixStats** will probably need to re-export **MatrixGenerics** generics so as to provide a smooth transition for packages that currently `importFrom(DelayedMatrixStats, ...)`.

FYI my initial `NEWS` files are usually just "Added new package **BLAH** to Bioconductor.".

**Comment by PeteHaitch** [comment]
Have started on this but my week has been sidetracked by bigger things.
Will continue next week, still time to get in for next release

**Comment by const-ae** [comment]
Sure, no problem. If you need help with anything, let me know :)

**Comment by const-ae** [comment]
Hi Pete,  I just wanted to ping you about the status of the submission and if there is anything I can help you with it? 
I would like to submit `sparseMatrixStats` to BioConductor this release cycle as well. But I cannot go ahead as long as `MatrixGenerics` is not submitted.

**Comment by PeteHaitch** [comment]
Almost there. 
Just ironing out some bugs in **MatrixGenerics** I found when I tried integrating it into **DelayedMatrixStats**.

**Comment by const-ae** [comment]
It looks great. Thank you so much :)

**Comment by const-ae** [comment]
I guess we can close this one now (https://github.com/Bioconductor/Contributions/issues/1448#issuecomment-614401206). Thank you @PeteHaitch for taking care of the submission :)

And thank you all for the great collaboration, I am looking forward to to integrate `MatrixGenerics` in my packages and support all kinds of different matrices :)
